/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.artur.clinica.view;

/**
 *
 * @author artur
 */
public class CadastroPacientePanel extends javax.swing.JPanel {

    /**
     * Creates new form CadastroPacientePanel
     */
    public CadastroPacientePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PacienteNome = new javax.swing.JTextField();
        CPFPaciente = new javax.swing.JFormattedTextField();
        DataNascimento = new javax.swing.JFormattedTextField();
        TipoSanguineo = new javax.swing.JComboBox<>();
        Alergias = new javax.swing.JTextField();
        CPFText = new javax.swing.JLabel();
        TipoSanguineoText = new javax.swing.JLabel();
        DataNasicmentoText = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 1, 1));
        setToolTipText("");

        PacienteNome.setText("Digite o nome do paciente...");
        PacienteNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PacienteNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PacienteNomeFocusLost(evt);
            }
        });
        PacienteNome.addActionListener(this::PacienteNomeActionPerformed);

        try {
            CPFPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPFPaciente.setText("000.000.000-00");
        CPFPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CPFPaciente.addActionListener(this::CPFPacienteActionPerformed);

        DataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        DataNascimento.addActionListener(this::DataNascimentoActionPerformed);

        TipoSanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+", " " }));

        Alergias.setText("Digite as Alergias do Paciente se tiver");
        Alergias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AlergiasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AlergiasFocusLost(evt);
            }
        });
        Alergias.addActionListener(this::AlergiasActionPerformed);

        CPFText.setText("CPF");

        TipoSanguineoText.setText("TIpo Sanguíneo");

        DataNasicmentoText.setText("Data de Nascimento");

        Salvar.setText("Salvar");
        Salvar.addActionListener(this::SalvarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataNasicmentoText)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TipoSanguineoText)
                            .addGap(18, 18, 18)
                            .addComponent(TipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(Salvar))
                        .addComponent(PacienteNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CPFPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DataNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(CPFText))
                        .addComponent(Alergias, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(564, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CPFText)
                .addGap(7, 7, 7)
                .addComponent(CPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataNasicmentoText)
                .addGap(4, 4, 4)
                .addComponent(DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Alergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoSanguineoText)
                    .addComponent(TipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salvar))
                .addGap(0, 450, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PacienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacienteNomeActionPerformed

    private void CPFPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFPacienteActionPerformed

    private void DataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataNascimentoActionPerformed

    private void AlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlergiasActionPerformed

    private void PacienteNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PacienteNomeFocusGained
        if (PacienteNome.getText().equals("Digite o nome do paciente...")) {
        PacienteNome.setText("");
        PacienteNome.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_PacienteNomeFocusGained

    private void PacienteNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PacienteNomeFocusLost
                                        
        if (PacienteNome.getText().trim().isEmpty()) {
            PacienteNome.setText("Digite o nome do paciente...");
            PacienteNome.setForeground(java.awt.Color.GRAY); 
        }
    }//GEN-LAST:event_PacienteNomeFocusLost

    private void AlergiasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AlergiasFocusGained
        if (Alergias.getText().equals("Digite as Alergias do Paciente se tiver")) {
        Alergias.setText("");
        Alergias.setForeground(java.awt.Color.BLACK); 
        }
    }//GEN-LAST:event_AlergiasFocusGained

    private void AlergiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AlergiasFocusLost
        if (Alergias.getText().trim().isEmpty()) {
            Alergias.setText("Digite as Alergias do Paciente se tiver");
            Alergias.setForeground(java.awt.Color.GRAY); 
        }
    }//GEN-LAST:event_AlergiasFocusLost

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        limparCampos();
    }//GEN-LAST:event_SalvarActionPerformed
    
    private void limparCampos(){
        PacienteNome.setText("");
        CPFPaciente.setValue(null);
        TipoSanguineo.setSelectedIndex(0);
        DataNascimento.setValue(null);
        Alergias.setText("");
        
        PacienteNome.setText("Digite o nome do paciente...");
        PacienteNome.setForeground(java.awt.Color.GRAY);
        
        Alergias.setText("Digite as Alergias do Paciente se tiver");
        Alergias.setForeground(java.awt.Color.GRAY); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alergias;
    private javax.swing.JFormattedTextField CPFPaciente;
    private javax.swing.JLabel CPFText;
    private javax.swing.JFormattedTextField DataNascimento;
    private javax.swing.JLabel DataNasicmentoText;
    private javax.swing.JTextField PacienteNome;
    private javax.swing.JButton Salvar;
    private javax.swing.JComboBox<String> TipoSanguineo;
    private javax.swing.JLabel TipoSanguineoText;
    // End of variables declaration//GEN-END:variables
}
