/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.artur.clinica.view;

/**
 *
 * @author artur
 */
public class CadastroMedicoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CastratoMedicoPanel
     */
    public CadastroMedicoPanel() {
        initComponents();
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Especialidades = new javax.swing.JTextField();
        CRMText = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        MedicoNome = new javax.swing.JTextField();
        CRM = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 1, 1));

        Especialidades.setText("Digite a Especialidade do Médico...");
        Especialidades.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EspecialidadesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EspecialidadesFocusLost(evt);
            }
        });
        Especialidades.addActionListener(this::EspecialidadesActionPerformed);

        CRMText.setText("CRM");

        Salvar.setText("Salvar");
        Salvar.addActionListener(this::SalvarActionPerformed);

        MedicoNome.setText("Digite o nome do Médico...");
        MedicoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MedicoNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MedicoNomeFocusLost(evt);
            }
        });
        MedicoNome.addActionListener(this::MedicoNomeActionPerformed);

        try {
            CRM.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#/UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CRM.setText("00000000-0/MT");
        CRM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CRM.addActionListener(this::CRMActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MedicoNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CRM, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(CRMText))
                        .addComponent(Especialidades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addComponent(Salvar))
                .addContainerGap(574, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MedicoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CRMText)
                .addGap(7, 7, 7)
                .addComponent(CRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Especialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salvar)
                .addGap(0, 512, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EspecialidadesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EspecialidadesFocusGained
        if (Especialidades.getText().equals("Digite a Especialidade do Médico...")) {
            Especialidades.setText("");
            Especialidades.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_EspecialidadesFocusGained

    private void EspecialidadesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EspecialidadesFocusLost
        if (Especialidades.getText().trim().isEmpty()) {
            Especialidades.setText("Digite a Especialidade do Médico...");
            Especialidades.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_EspecialidadesFocusLost

    private void EspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadesActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        limparCampos();
    }//GEN-LAST:event_SalvarActionPerformed

    private void MedicoNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MedicoNomeFocusGained
        if (MedicoNome.getText().equals("Digite o nome do Médico...")) {
            MedicoNome.setText("");
            MedicoNome.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_MedicoNomeFocusGained

    private void MedicoNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MedicoNomeFocusLost
    
        if (MedicoNome.getText().trim().isEmpty()) {
            MedicoNome.setText("Digite o nome do Médico...");
            MedicoNome.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_MedicoNomeFocusLost
    
    private void limparCampos(){
        MedicoNome.setText("");
        CRM.setValue(null);
        Especialidades.setText("");
        
        MedicoNome.setText("Digite o nome do Médico...");
        MedicoNome.setForeground(java.awt.Color.GRAY);
        
        Especialidades.setText("Digite a Especialidade do Médico...");
        Especialidades.setForeground(java.awt.Color.GRAY); 
    }
    
    private void MedicoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicoNomeActionPerformed

    private void CRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CRMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CRM;
    private javax.swing.JLabel CRMText;
    private javax.swing.JTextField Especialidades;
    private javax.swing.JTextField MedicoNome;
    private javax.swing.JButton Salvar;
    // End of variables declaration//GEN-END:variables
}
