FROM eclipse-temurin:17-jdk


RUN apt-get update && apt-get install -y \
    openssh-server \
    maven \
    bash \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /var/run/sshd


RUN ssh-keygen -A || true

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config


RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh


COPY authorized_keys /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys


WORKDIR /workspace


EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]