/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author artur
 */
public class OperacoesTabela extends javax.swing.JPanel {

    /**
     * Creates new form OperacoesPanel
     */
    public OperacoesTabela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmarDelete = new javax.swing.JDialog();
        ConfirmarText = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        TabelaScroll = new javax.swing.JScrollPane();
        TabelaRegistros = new javax.swing.JTable();
        RegistrosSalvosText = new javax.swing.JLabel();
        Editar = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        BarraBusca = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();

        ConfirmarDelete.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ConfirmarDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfirmarDelete.setLocation(new java.awt.Point(0, 0));
        ConfirmarDelete.setLocationByPlatform(true);
        ConfirmarDelete.setMinimumSize(new java.awt.Dimension(400, 200));
        ConfirmarDelete.setResizable(false);

        ConfirmarText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConfirmarText.setText("Confirmar a Deleção da Consulta");

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(this::ConfirmarActionPerformed);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::CancelarActionPerformed);

        javax.swing.GroupLayout ConfirmarDeleteLayout = new javax.swing.GroupLayout(ConfirmarDelete.getContentPane());
        ConfirmarDelete.getContentPane().setLayout(ConfirmarDeleteLayout);
        ConfirmarDeleteLayout.setHorizontalGroup(
            ConfirmarDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmarDeleteLayout.createSequentialGroup()
                .addGroup(ConfirmarDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfirmarDeleteLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(ConfirmarText))
                    .addGroup(ConfirmarDeleteLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Confirmar)
                        .addGap(73, 73, 73)
                        .addComponent(Cancelar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        ConfirmarDeleteLayout.setVerticalGroup(
            ConfirmarDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmarDeleteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ConfirmarText)
                .addGap(53, 53, 53)
                .addGroup(ConfirmarDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmar)
                    .addComponent(Cancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 1, 1));

        TabelaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ticket", "Paciente", "Data", "Horário", "Médico"
            }
        ));
        TabelaRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabelaScroll.setViewportView(TabelaRegistros);

        RegistrosSalvosText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RegistrosSalvosText.setText("Registros Salvos");

        Editar.setText("Editar");
        Editar.addActionListener(this::EditarActionPerformed);

        Deletar.setText("Deletar");
        Deletar.addActionListener(this::DeletarActionPerformed);

        BarraBusca.addActionListener(this::BarraBuscaActionPerformed);

        BuscarButton.setText("🔍");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BarraBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Deletar)
                        .addGap(18, 18, 18)
                        .addComponent(Editar)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TabelaScroll, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                                .addComponent(RegistrosSalvosText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(RegistrosSalvosText)
                .addGap(18, 18, 18)
                .addComponent(TabelaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editar)
                    .addComponent(Deletar)
                    .addComponent(BarraBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarActionPerformed

    private void DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarActionPerformed
        
        ConfirmarDelete.setVisible(true);
        
    }//GEN-LAST:event_DeletarActionPerformed

    private void BarraBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraBuscaActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        ConfirmarDelete.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
     
        int selected = TabelaRegistros.getSelectedRow();
        if(selected >=0){
            String CodTicket = TabelaRegistros.getValueAt(selected,1).toString();
        }
        ConfirmarDelete.dispose();
    }//GEN-LAST:event_ConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraBusca;
    private javax.swing.JButton BuscarButton;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Confirmar;
    private javax.swing.JDialog ConfirmarDelete;
    private javax.swing.JLabel ConfirmarText;
    private javax.swing.JButton Deletar;
    private javax.swing.JButton Editar;
    private javax.swing.JLabel RegistrosSalvosText;
    private javax.swing.JTable TabelaRegistros;
    private javax.swing.JScrollPane TabelaScroll;
    // End of variables declaration//GEN-END:variables
}
